// Detailed product data array
products = [
  {
    id: 1001,
    title: "Math Club",
    subject: "Math",
    location: "123 Math Lane",
    price: 100,
    availableInventory: 5,
    image: "images/math-fullsize.png",
    rating: 4,
  },
  {
    id: 1002,
    title: "English Club",
    subject: "English",
    location: "456 English Ave",
    price: 500,
    availableInventory: 5,
    image: "images/english-fullsize.jpg",
    rating: 5,
  },
  {
    id: 1003,
    title: "Arabic Club",
    subject: "Arabic",
    location: "789 Arabic Street",
    price: 500,
    availableInventory: 5,
    image: "images/arabic-fullsize.png",
    rating: 3,
  },
  {
    id: 1004,
    title: "Physics Club",
    subject: "Physics",
    location: "101 Physics Blvd",
    price: 500,
    availableInventory: 5,
    image: "images/physics-fullsize.jpg",
    rating: 5,
  },
  {
    id: 1005,
    title: "Chemistry Club",
    subject: "Chemistry",
    location: "202 Chemistry Road",
    price: 500,
    availableInventory: 5,
    image: "images/chemistry-fullsize.jpg",
    rating: 4,
  },
  {
    id: 1006,
    title: "Art Club",
    subject: "Art",
    location: "202 art Road",
    price: 300,
    availableInventory: 5,
    image: "images/art-fullsize.avif",
    rating: 4,
  },
  {
    id: 1007,
    title: "Biology Club",
    subject: "Biology",
    location: "202 Biology Road",
    price: 800,
    availableInventory: 5,
    image: "images/biology-fullsize.jpg",
    rating: 5,
  },
  {
    id: 1008,
    title: "Cyber Security Club",
    subject: "Cyber Security",
    location: "202 Chemistry Road",
    price: 600,
    availableInventory: 5,
    image: "images/cybersecurity-fullsize.avif",
    rating: 4,
  },
  {
    id: 1009,
    title: "Economics Club",
    subject: "Economics",
    location: "202 Chemistry Road",
    price: 500,
    availableInventory: 5,
    image: "images/economics-fullsize.webp",
    rating: 4,
  },
  {
    id: 1010,
    title: "French Club",
    subject: "French",
    location: "202 Chemistry Road",
    price: 400,
    availableInventory: 5,
    image: "images/french-fullsize.webp",
    rating: 4,
  },
  {
    id: 1011,
    title: "Finance Club",
    subject: "Finance",
    location: "202 Chemistry Road",
    price: 600,
    availableInventory: 5,
    image: "images/finance-fullsize.avif",
    rating: 4,
  },
  {
    id: 1012,
    title: "AI Club",
    subject: "Artificial Intelligence",
    location: "202 Chemistry Road",
    price: 500,
    availableInventory: 5,
    image: "images/ai-fullsize.avif",
    rating: 4,
  },
];
